# Generated by Django 5.1.6 on 2025-02-13 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='role',
            field=models.CharField(default='manager', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='branch_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='manager_name',
            field=models.CharField(max_length=255),
        ),
    ]
